name: Feature Request

description: Nueva funcionalidad

title: "[FEATURE]: "

labels:
  - feature

body:
  - type: textarea
    id: problem
    attributes:
      label: Problema

  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
